# Unit-test (kinda)

In [1]:
# Really quick-test
!python model.py
!python loss.py
#!python loupe.py

Traceback (most recent call last):
  File "model.py", line 291, in <module>
    a, b, c, d = net(y_padded, z, x, x, x)
  File "/mnt/ilcompf9d1/user/escorcia/install/bin/miniconda3/envs/scientific/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "model.py", line 52, in forward
    last_output = output[range(B), query_length - 1, :]
TypeError: unsupported operand type(s) for -: 'list' and 'int'


In [17]:
# This takes a couple of minutes
!python didemo.py

/home/escorciav/install/bin/miniconda3/envs/scientific/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
simple test
Time loading data/raw/train_data.json:  114.0846495628357
33005
{'num_segments': 6, 'description': "a brown rat goes into someone's hand then onto a cage.", 'dl_link': 'https://www.flickr.com/video_download.gne?id=2408598493', 'times': [[2, 2], [2, 2], [2, 2], [2, 2]], 'video': '54322086@N00_2408598493_274c77d26a.avi', 'annotation_id': 2, 'language_input': ['a', 'brown', 'rat', 'goes', 'into', 'someone', 's', 'hand', 'then', 'onto', 'a', 'cage']}
0 (50, 300)
1 12
rgb (8194,)
flow (2050,)
rgb (8194,)
flow (2050,)
rgb (8194,)
flow (2050,)
0 (21, 50, 300)
1 21
rgb (21, 8194)
flow (21, 2050)


# TODO

- Add NetVLAD

- Experiment NetVLAD vs LSTM

# Bash

Test training loop
```bash
for i in {001..015}; do python train.py --epochs 2 --gpu-id 1 &> $i".log"; done
```

# Sandbox

Always stacking, It's better than scrolling :)

In [17]:
import torch

x = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(x)
n = x.size()[0]        
x1 = torch.diag(x)
print(x1.shape)
print(x1)
x1 = x1.expand(n, n)
print(x1.shape)
print(x1)
x1 = x1.contiguous().view(-1,1)
print(x1.shape)
print(x1)
x1 = torch.cat((x1, x1),0) 

x2 = x.view(-1, 1)
print(x2)
x3 = x.transpose(0, 1).contiguous().view(-1,1)
print(x3)

x2 = torch.cat((x2,x3),0)

y = (1 - torch.eye(n)).view(-1, 1)
print(y)

tensor([[ 11,  12,  13],
        [ 21,  22,  23],
        [ 31,  32,  33]])
torch.Size([3])
tensor([ 11,  22,  33])
torch.Size([3, 3])
tensor([[ 11,  22,  33],
        [ 11,  22,  33],
        [ 11,  22,  33]])
torch.Size([9, 1])
tensor([[ 11],
        [ 22],
        [ 33],
        [ 11],
        [ 22],
        [ 33],
        [ 11],
        [ 22],
        [ 33]])
tensor([[ 11],
        [ 12],
        [ 13],
        [ 21],
        [ 22],
        [ 23],
        [ 31],
        [ 32],
        [ 33]])
tensor([[ 11],
        [ 21],
        [ 31],
        [ 12],
        [ 22],
        [ 32],
        [ 13],
        [ 23],
        [ 33]])
tensor([[ 0.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 0.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 0.]])


In [12]:
from torch.utils.data import Dataset, DataLoader

class Simple(Dataset):
    def __init__(self):
        self.x = list(range(5))
        
    def __len__(self):
        return len(self.x)
    
    def __getitem__(self, idx):
        x = self.x[idx]
        return x * 2, {'x': x, 'y': x + 5}
    
data = Simple()
data[0]

loader = DataLoader(data)

for i in loader:
    print(i)

[tensor([ 0]), {'x': tensor([ 0]), 'y': tensor([ 5])}]
[tensor([ 2]), {'x': tensor([ 1]), 'y': tensor([ 6])}]
[tensor([ 4]), {'x': tensor([ 2]), 'y': tensor([ 7])}]
[tensor([ 6]), {'x': tensor([ 3]), 'y': tensor([ 8])}]
[tensor([ 8]), {'x': tensor([ 4]), 'y': tensor([ 9])}]


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import math


class NetVLAD(nn.Module):
    
    def __init__(self, cluster_size, feature_size, add_batch_norm=True):
        super(NetVLAD, self).__init__()
        self.feature_size = feature_size
        self.cluster_size = cluster_size
        self.add_batch_norm = add_batch_norm
        self.out_dim = cluster_size * feature_size
        self.clusters = nn.Parameter(
            (1 / math.sqrt(feature_size)) * torch.randn(feature_size, cluster_size))
        self.clusters2 = nn.Parameter(
            (1 / math.sqrt(feature_size)) * th.randn(1, feature_size, cluster_size))
        if add_batch_norm:
            self.batch_norm = nn.BatchNorm1d(cluster_size)

    def forward(self, x):
        max_sample = x.shape[1]
        x = x.view(-1, self.feature_size)
        assignment = th.matmul(x, self.clusters)

        if self.add_batch_norm:
            assignment = self.batch_norm(assignment)

        assignment = F.softmax(assignment, dim=1)
        assignment = assignment.view(-1, max_sample, self.cluster_size)

        a_sum = th.sum(assignment, -2, keepdim=True)
        a = a_sum * self.clusters2
        assignment = assignment.transpose(1, 2)

        x = x.view(-1, max_sample, self.feature_size)
        vlad = th.matmul(assignment, x)
        vlad = vlad.transpose(1, 2)
        vlad = vlad - a

        # L2 intra norm
        vlad = F.normalize(vlad)
        
        # flattening + L2 norm
        vlad = vlad.view(-1, self.cluster_size * self.feature_size)
        vlad = F.normalize(vlad)

        return vlad

class NetRVLAD(nn.Module):
    
    def __init__(self, cluster_size, feature_size, add_batch_norm=True):
        super(NetRVLAD, self).__init__()
        self.feature_size = feature_size
        self.cluster_size = cluster_size
        self.add_batch_norm = add_batch_norm
        self.out_dim = cluster_size * feature_size
        self.clusters = nn.Parameter(
            (1 / math.sqrt(feature_size)) * th.randn(feature_size, cluster_size))
        if self.add_batch_norm:
            self.batch_norm = nn.BatchNorm1d(cluster_size)

    def forward(self,x):
        max_sample = x.shape[1]
        x = x.view(-1, self.feature_size)
        assignment = th.matmul(x, self.clusters)

        if self.add_batch_norm:
            assignment = self.batch_norm(assignment)

        assignment = F.softmax(assignment, dim=1)
        assignment = assignment.view(-1, max_sample, self.cluster_size)
        assignment = assignment.transpose(1, 2)

        x = x.view(-1, max_sample, self.feature_size)
        rvlad = th.matmul(assignment, x)
        rvlad = rvlad.transpose(-1, 1)

        # L2 intra norm
        rvlad = F.normalize(rvlad)
        
        # flattening + L2 norm
        rvlad = rvlad.view(-1, self.cluster_size * self.feature_size)
        rvlad = F.normalize(rvlad)

        return rvlad

# Debugging

- Used to check if parameter are changing

```python
for k, v in net.img_encoder.named_parameters(): print(k, v.sum())
for k, v in net.sentence_encoder.named_parameters(): print(k, v.sum())
```

- Pick last step of LSTM

In [3]:
import torch
import torch.nn as nn

batch_size = 4
max_length = 3
hidden_size = 2
n_layers = 1
input_dim = 1
batch_first = True

# Data
vec_1 = torch.FloatTensor([[1, 2, 3]])
vec_2 = torch.FloatTensor([[1, 2, 0]])
vec_3 = torch.FloatTensor([[1, 0, 0]])
vec_4 = torch.FloatTensor([[2, 0, 0]])

# Put the data into a tensor.
batch_in = torch.cat([vec_1, vec_2, vec_3, vec_4])
batch_in = torch.unsqueeze(batch_in, -1)

# Wrap RNN input in a Variable. Shape: (batch_size, max_length, input_dim)
# The lengths of each example in the batch. Padding is 0.
lengths = torch.LongTensor([3, 2, 1, 1])

# Wrap input in packed sequence, with batch_first=True
packed_input = torch.nn.utils.rnn.pack_padded_sequence(
    batch_in, lengths, batch_first=True)

# Create an RNN object, set batch_first=True
rnn = nn.RNN(input_dim, hidden_size, n_layers, batch_first=True) 

# Run input through RNN 
packed_output, _ = rnn(packed_input)

# Unpack, with batch_first=True.
output, _ = torch.nn.utils.rnn.pad_packed_sequence(
    packed_output, batch_first=True)
print("Unpacked, padded output: ")
print(output)
last_step = output[range(batch_size), lengths - 1, :]
print(last_step)

Unpacked, padded output: 
tensor([[[-0.8222,  0.7389],
         [-0.8997,  0.7998],
         [-0.9645,  0.8589]],

        [[-0.8222,  0.7389],
         [-0.8997,  0.7998],
         [ 0.0000,  0.0000]],

        [[-0.8222,  0.7389],
         [ 0.0000,  0.0000],
         [ 0.0000,  0.0000]],

        [[-0.9388,  0.8147],
         [ 0.0000,  0.0000],
         [ 0.0000,  0.0000]]])
tensor([[-0.9645,  0.8589],
        [-0.8997,  0.7998],
        [-0.8222,  0.7389],
        [-0.9388,  0.8147]])
